name: 1. Generate Data (08:30)

on:
  schedule:
    - cron: '30 8 * * *' # 08:30 UTC
  workflow_dispatch:

jobs:
  generate_traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install posthog
      - name: Generate Traffic
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
        run: python automation/daily_pulse.py